// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOATj9nfbNFDazG197uMR4HUF40p1nNMU',
    appId: '1:897301427959:web:d66a919b24b03cc53f45f2',
    messagingSenderId: '897301427959',
    projectId: 'vischeck-63885',
    authDomain: 'vischeck-63885.firebaseapp.com',
    storageBucket: 'vischeck-63885.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7YdfgYIj7G2ZaNWo56LjhelqDThUt9w4',
    appId: '1:897301427959:android:bc67aae30db0b94b3f45f2',
    messagingSenderId: '897301427959',
    projectId: 'vischeck-63885',
    storageBucket: 'vischeck-63885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Dm85awEQIeAyOug5BjWKwo-GTITqzTo',
    appId: '1:897301427959:ios:93981d82adba3a1b3f45f2',
    messagingSenderId: '897301427959',
    projectId: 'vischeck-63885',
    storageBucket: 'vischeck-63885.firebasestorage.app',
    iosBundleId: 'com.example.firstproj',
  );
}
